fix: linting

diff --git a/lsix b/lsix
--- a/lsix
+++ b/lsix
@@ -10,16 +10,15 @@
 
 # See end of file for USAGE.
 
-
 # The following defaults may be overridden if autodetection succeeds.
 numcolors=16     # Default number of colors in the palette.
 background=white # Default montage background.
 foreground=black # Default text color.
-width=800	 # Default width of screen in pixels.
+width=800        # Default width of screen in pixels.
 
 # Feel free to edit these defaults to your liking.
-tilesize=120	       # Width and height of each tile in the montage.
-tilewidth=$tilesize    # (or specify separately, if you prefer)
+tilesize=120        # Width and height of each tile in the montage.
+tilewidth=$tilesize # (or specify separately, if you prefer)
 tileheight=$tilesize
 
 # If you get questionmarks for Unicode filenames, try using a different font.
@@ -29,16 +28,16 @@ tileheight=$tilesize
 #fontfamily=Mincho			# Wide coverage, comes with MS Windows
 
 # Default font size is based on width of each tile in montage.
-fontsize=$((tilewidth/10))
+fontsize=$((tilewidth / 10))
 #fontsize=16		     # (or set the point size directly, if you prefer)
 
-timeout=0.25		    # How long to wait for terminal to respond
-			    # to a control sequence (in seconds).
+timeout=0.25 # How long to wait for terminal to respond
+# to a control sequence (in seconds).
 
 # Sanity checks and compatibility
 if [[ ${BASH_VERSINFO[0]} -eq 3 ]]; then
     if bash --version | head -1 | grep -q "version 3"; then
-	cat <<-EOF >&2
+        cat <<-EOF >&2
 	Error: The version of Bash is extremely out of date.
 	(2007, the same year Steve Jobs announced the iPhone!)
 
@@ -47,10 +46,10 @@ if [[ ${BASH_VERSINFO[0]} -eq 3 ]]; then
 
 	In the meantime, try using "brew install bash".
 	EOF
-	exit 1
+        exit 1
     else
-	exec bash "$0" "$@"  || echo "Exec failed" >&2
-	exit 1
+        exec bash "$0" "$@" || echo "Exec failed" >&2
+        exit 1
     fi
 fi
 
@@ -59,19 +58,19 @@ if ! command -v montage >/dev/null; then
     exit 1
 fi
 
-shopt -s expand_aliases		# Allow aliases for working around quirks.
+shopt -s expand_aliases # Allow aliases for working around quirks.
 
 if command -v gsed >/dev/null; then
-    alias sed=gsed		# Use GNU sed for MacOS & BSD.
+    alias sed=gsed # Use GNU sed for MacOS & BSD.
 fi
 
 if [[ "$COMSPEC" ]]; then
     alias convert="magick convert" # Shun MS Windows' "convert" command.
 fi
-    
+
 cleanup() {
-    echo -n $'\e\\'		# Escape sequence to stop SIXEL.
-    stty echo			# Reset terminal to show characters.
+    echo -n $'\e\\' # Escape sequence to stop SIXEL.
+    stty echo       # Reset terminal to show characters.
     exit 0
 }
 trap cleanup SIGINT SIGHUP SIGABRT EXIT
@@ -80,22 +79,22 @@ autodetect() {
     # Various terminal automatic configuration routines.
 
     # Don't show escape sequences the terminal doesn't understand.
-    stty -echo			# Hush-a Mandara Ni Pari
+    stty -echo # Hush-a Mandara Ni Pari
 
     # IS TERMINAL SIXEL CAPABLE?		# Send Device Attributes
     IFS=";?c" read -a REPLY -s -t 1 -d "c" -p $'\e[c' >&2
     for code in "${REPLY[@]}"; do
-	if [[ $code == "4" ]]; then
-	    hassixel=yup
-	    break
-	fi
+        if [[ $code == "4" ]]; then
+            hassixel=yup
+            break
+        fi
     done
 
     # YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
     if [[ "$TERM" == yaft* ]]; then hassixel=yeah; fi
 
     if [[ -z "$hassixel" && -z "$LSIX_FORCE_SIXEL_SUPPORT" ]]; then
-	cat <<-EOF >&2
+        cat <<-EOF >&2
 	Error: Your terminal does not report having sixel graphics support.
 
 	Please use a sixel capable terminal, such as xterm -ti vt340, or
@@ -108,13 +107,13 @@ autodetect() {
 	If your terminal actually does support sixel, please file a bug
 	report at http://github.com/hackerb9/lsix/issues
 	EOF
-	read -s -t 1 -d "c" -p $'\e[c' >&2
-	if [[ "$REPLY" ]]; then
-	    echo
-	    cat -v <<< "Please mention device attribute codes: ${REPLY}c"
-	fi
+        read -s -t 1 -d "c" -p $'\e[c' >&2
+        if [[ "$REPLY" ]]; then
+            echo
+            cat -v <<<"Please mention device attribute codes: ${REPLY}c"
+        fi
 
-	exit 1
+        exit 1
     fi
 
     # SIXEL SCROLLING (~DECSDM) is now presumed to be enabled.
@@ -122,7 +121,7 @@ autodetect() {
 
     # TERMINAL COLOR AUTODETECTION.
     # Find out how many color registers the terminal has
-    IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;1;0S' >&2
+    IFS=";" read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;1;0S' >&2
     [[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
 
     # YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
@@ -130,55 +129,58 @@ autodetect() {
 
     # Increase colors, if needed
     if [[ $numcolors -lt 256 ]]; then
-	# Attempt to set the number of colors to 256.
-	# This will work for xterm, but fail on a real vt340.
-	IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;3;256S' >&2
-	[[ ${REPLY[1]} == "0" && ${REPLY[2]} -gt 0 ]] && numcolors=${REPLY[2]}
+        # Attempt to set the number of colors to 256.
+        # This will work for xterm, but fail on a real vt340.
+        IFS=";" read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;3;256S' >&2
+        [[ ${REPLY[1]} == "0" && ${REPLY[2]} -gt 0 ]] && numcolors=${REPLY[2]}
     fi
 
     # Query the terminal background and foreground colors.
-    IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
+    IFS=";:/" read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
     if [[ ${REPLY[1]} =~ ^rgb ]]; then
-	# Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
-	# ImageMagick wants colors formatted as #ffff0000ffff.
-	background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
-	IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
-	if [[ ${REPLY[1]} =~ ^rgb ]]; then
-	    foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
-	    # Check for "Reverse Video" (DECSCNM screen mode).
-	    IFS=";?$"  read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
-	    if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
-		temp=$foreground
-		foreground=$background
-		background=$temp
-	    fi
-	fi
+        # Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
+        # ImageMagick wants colors formatted as #ffff0000ffff.
+        background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+        IFS=";:/" read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
+        if [[ ${REPLY[1]} =~ ^rgb ]]; then
+            foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+            # Check for "Reverse Video" (DECSCNM screen mode).
+            IFS=";?$" read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
+            if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
+                temp=$foreground
+                foreground=$background
+                background=$temp
+            fi
+        fi
     fi
     # YAFT is vt102 compatible, cannot respond to vt220 escape sequence.
-    if [[ "$TERM" == yaft* ]]; then background=black; foreground=white; fi
+    if [[ "$TERM" == yaft* ]]; then
+        background=black
+        foreground=white
+    fi
 
     # Send control sequence to query the sixel graphics geometry to
     # find out how large of a sixel image can be shown.
-    IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?2;1;0S' >&2
+    IFS=";" read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?2;1;0S' >&2
     if [[ ${REPLY[2]} -gt 0 ]]; then
-	width=${REPLY[2]}
+        width=${REPLY[2]}
     else
-	# Nope. Fall back to dtterm WindowOps to approximate sixel geometry.
-	IFS=";" read -a REPLY -s -t ${timeout} -d "t" -p $'\e[14t' >&2
-	if [[ $? == 0  &&  ${REPLY[2]} -gt 0 ]]; then
-	    width=${REPLY[2]}
-	fi
+        # Nope. Fall back to dtterm WindowOps to approximate sixel geometry.
+        IFS=";" read -a REPLY -s -t ${timeout} -d "t" -p $'\e[14t' >&2
+        if [[ $? == 0 && ${REPLY[2]} -gt 0 ]]; then
+            width=${REPLY[2]}
+        fi
     fi
 
     # BUG WORKAROUND: XTerm cannot show images wider than 1000px.
     # Remove this hack once XTerm gets fixed. Last checked: XTerm(344)
-    if [[ $TERM =~ xterm && $width -ge 1000 ]]; then  width=1000; fi
+    if [[ $TERM =~ xterm && $width -ge 1000 ]]; then width=1000; fi
 
     # Space on either side of each tile is less than 0.5% of total screen width
-    tilexspace=$((width/201))
-    tileyspace=$((tilexspace/2))
+    tilexspace=$((width / 201))
+    tileyspace=$((tilexspace / 2))
     # Figure out how many tiles we can fit per row. ("+ 1" is for -shadow).
-    numtiles=$((width/(tilewidth + 2*tilexspace + 1)))
+    numtiles=$((width / (tilewidth + 2 * tilexspace + 1)))
 }
 
 main() {
@@ -186,66 +188,68 @@ main() {
     autodetect
 
     if [[ $# == 0 ]]; then
-	# No command line args? Use a sorted list of image files in CWD.
-	shopt -s nullglob nocaseglob nocasematch
-	set -- *{jpg,jpeg,png,gif,webp,tiff,tif,p?m,x[pb]m,bmp,ico,svg,eps}
-	[[ $# != 0 ]] || exit
-	readarray -t < <(printf "%s\n" "$@" | sort)
+        # No command line args? Use a sorted list of image files in CWD.
+        shopt -s nullglob nocaseglob nocasematch
+        set -- *{jpg,jpeg,png,gif,webp,tiff,tif,p?m,x[pb]m,bmp,ico,svg,eps}
+        [[ $# != 0 ]] || exit
+        readarray -t < <(printf "%s\n" "$@" | sort)
 
-	# Only show first frame of animated GIFs if filename not specified.
-	for x in ${!MAPFILE[@]}; do
-	    if [[ ${MAPFILE[$x]} =~ (gif|webp)$ ]]; then
-		MAPFILE[$x]="${MAPFILE[$x]}[0]"
-	    fi
-	done
-	set -- "${MAPFILE[@]}"
+        # Only show first frame of animated GIFs if filename not specified.
+        for x in "${!MAPFILE[@]}"; do
+            if [[ ${MAPFILE[$x]} =~ (gif|webp)$ ]]; then
+                MAPFILE[$x]="${MAPFILE[$x]}[0]"
+            fi
+        done
+        set -- "${MAPFILE[@]}"
     else
-	# Command line args specified. Check for directories.
-	lsix=$(realpath "$0")
-	for arg; do
-	    if [ -d "$arg" ]; then
-		echo Recursing on $arg
-		(cd "$arg"; $lsix)
-	    else
-		nodirs+=("$arg")
-	    fi
-	done
-	set -- "${nodirs[@]}"
+        # Command line args specified. Check for directories.
+        lsix=$(realpath "$0")
+        for arg; do
+            if [ -d "$arg" ]; then
+                echo Recursing on $arg
+                (
+                    cd "$arg" || exit
+                    $lsix
+                )
+            else
+                nodirs+=("$arg")
+            fi
+        done
+        set -- "${nodirs[@]}"
     fi
-
 
     # Resize on load: Save memory by appending this suffix to every filename.
     resize="[${tilewidth}x${tileheight}]"
 
-    imoptions="-tile ${numtiles}x1" # Each montage is 1 row x $numtiles columns
+    imoptions="-tile ${numtiles}x1"                                                 # Each montage is 1 row x $numtiles columns
     imoptions+=" -geometry ${tilewidth}x${tileheight}>+${tilexspace}+${tileyspace}" # Size of each tile and spacing
-    imoptions+=" -background $background -fill $foreground" # Use terminal's colors
-    imoptions+=" -auto-orient "	# Properly rotate JPEGs from cameras
+    imoptions+=" -background $background -fill $foreground"                         # Use terminal's colors
+    imoptions+=" -auto-orient "                                                     # Properly rotate JPEGs from cameras
     if [[ $numcolors -gt 16 ]]; then
-	imoptions+=" -shadow "		# Just for fun :-)
+        imoptions+=" -shadow " # Just for fun :-)
     fi
 
     # See top of this file to change fontfamily and fontsize.
-    [[ "$fontfamily" ]]  &&  imoptions+=" -font $fontfamily "
-    [[ "$fontsize" ]] &&     imoptions+=" -pointsize $fontsize "
+    [[ "$fontfamily" ]] && imoptions+=" -font $fontfamily "
+    [[ "$fontsize" ]] && imoptions+=" -pointsize $fontsize "
 
     # Create and display montages one row at a time.
-		while [ $# -gt 0 ]; do
-				# While we still have images to process...
-				onerow=()
-				goal=$(($# - numtiles)) # How many tiles left after this row
-				while [ $# -gt 0 ] && [ $# -gt $goal ]; do
-						len=${#onerow[@]}
-						onerow[len++]="-label"
-						onerow[len++]="$(processlabel "$1")"
-						onerow[len++]="file://$1"
-						shift
-				done
+    while [ $# -gt 0 ]; do
+        # While we still have images to process...
+        onerow=()
+        goal=$(($# - numtiles)) # How many tiles left after this row
+        while [ $# -gt 0 ] && [ $# -gt $goal ]; do
+            len=${#onerow[@]}
+            onerow[len++]="-label"
+            onerow[len++]="$(processlabel "$1")"
+            onerow[len++]="file://$1"
+            shift
+        done
 
-				montage "${onerow[@]}" $imoptions gif:- \
-						| magick - -colors $numcolors sixel:-  # Convert to magick here.
+        montage "${onerow[@]}" $imoptions gif:- |
+            magick - -colors $numcolors sixel:- # Convert to magick here.
 
-		done
+    done
 }
 
 processlabel() {
@@ -255,10 +259,10 @@ processlabel() {
     # 3. Replace control characters with question marks.
     # 4. If a filename is too long, remove extension (.jpg).
     # 5. Split long filenames with newlines (recursively)
-    span=15			# filenames longer than span will be split
+    span=15 # filenames longer than span will be split
     echo -n "$1" |
-	sed 's|^:||; s|\[0]$||;' | tr '[:cntrl:]' '?' |
-	awk -v span=$span -v ORS=""  '
+        sed 's|^:||; s|\[0]$||;' | tr '[:cntrl:]' '?' |
+        awk -v span=$span -v ORS="" '
 	function halve(s,      l,h) {	# l and h are locals
 	    l=length(s);  h=int(l/2);
 	    if (l <= span) { return s; }
@@ -269,7 +273,7 @@ processlabel() {
 	  print halve($0);
 	}
 	' |
-	sed 's|%|%%|g; s|\\|\\\\|g; s|@|\\@|g;'
+        sed 's|%|%%|g; s|\\|\\\\|g; s|@|\\@|g;'
 }
 
 ####
@@ -279,7 +283,6 @@ main "$@"
 # Send an escape sequence and wait for a response from the terminal
 # so that the program won't quit until images have finished transferring.
 read -s -t 60 -d "c" -p $'\e[c' >&2
-
 
 ######################################################################
 # NOTES:
